[lib]
crate-type = ["cdylib", "staticlib"]

[package]
name = "rust-lib"
version = "0.1.0"
authors = ["Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>"]
edition = "2018"

[dependencies]
safer-ffi = { version = "0.0.5", features = ["proc_macros", "out-refs"] }

[workspace]

